name: 'Release Dilos'

on:
  workflow_call:
    inputs:
      version:
        description: 'The type of version to release.'
        type: string
        required: true
      tag:
        description: 'The tag to publish to NPM.'
        type: string
        required: true
      preid:
        description: 'The prerelease identifier used when doing a prerelease.'
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release-libs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/publish-npm
      with:
        scope: '@dilos/libs'
        tag: ${{ inputs.tag }}
        version: ${{ inputs.version }}
        preid: ${{ inputs.preid }}
        working-directory: 'packages/libs'
        token: ${{ secrets.NPM_TOKEN }}