name: 'Dilos Production Release'

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        description: Which version should be published?
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
      tag:
        required: true
        type: choice
        description: Which npm tag should this be published to?
        options:
          - latest
          - next
          - v5-lts
          - v4-lts
      preid:
        type: choice
        description: Which prerelease identifier should be used? This is only needed when version is "prepatch", "preminor", "premajor", or "prerelease".
        options:
          - ''
          - alpha
          - beta
          - rc
          - next

jobs:
  release-dilos:
    permissions:
      id-token: write
    uses: ./.github/workflows/release-dilos.yml
    with:
      tag: ${{ inputs.tag }}
      version: ${{ inputs.version }}
      preid: ${{ inputs.preid }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}